name: Ruby-Deploy-to-Production

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [master, dev]

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      container: 
        image: ruby:2.6.3
      
    steps:
      - uses: actions/checkout@v2
      - name: setup bundle
        run: bundle install
   
