name: Capistrano
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [master, dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@master
      with:
        ref: master
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.1.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }} # 1.で設定したsecretsを呼び出して鍵配置
    - name: Install Libmysqlclient-dev
      run: |
        sudo apt-get install libmysqlclient-dev
    - name: Bundle Update
      run: |
        bundle update --bundler
    - name: Bundle install
      run: |
        bundle install
    - name: Deploy Production
      run: |
        bundle exec cap production deploy
