name: Capistrano
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [master, dev]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ruby:2.6.6
      env:
         BUNDLER_VERSION: 2.1.4 
    
    steps:
      - uses: actions/checkout@v2
      - name: setup bundle
        run: bundle install
