name: Capistrano
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [master, dev]

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      container: 
        image: ruby:2.6.3
      
    steps:
      - uses: actions/checkout@v1
      - name: Prepare bundler
        run: |
          bundle install
