name: Capistrano
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [master, dev]

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      container: 
        image: ruby:2.6.3
      
    steps:
      - uses: actions/checkout@v1
      - run: gem install bundler --no-document
      - run: bundle config set deployment 'true'
      - run: bundle install --jobs 4 --retry 3
      - run: bundle exec rake

